### ISSUE TITLE
NLTK Version Incompatibility with spacy-wordnet

### ISSUE THREAD

**Issue by YanisaHS** [gutfeeling/word_forms#13]
Hey! Is there a reason the minimum nltk version was increased to 3.5, and not >=3.3 (or some other lower version)? Spacy-wordnet requires nltk 3.3, so word_forms isn't compatible with that at the moment. Thanks!

**Comment by gutfeeling** [comment]
Nope, no reason. Previously it had 3.2.1, but that one is insecure. So I bumped the version to the latest NLTK. If you think >=3.3 is better, feel free to send a pull request.
