### ISSUE TITLE
Host Package on pypi

### ISSUE THREAD

**Issue by JonnoFTW** [gutfeeling/word_forms#15]
Hi,

Can you please post this package on pypi?

**Comment by gutfeeling** [comment]
Thanks for the request. I will post here when I find the time to upload the package on pypi.

**Comment by tupui** [comment]
> Thanks for the request. I will post here when I find the time to upload the package on pypi.

@gutfeeling What is the status? You need some help? 😃

**Comment by tupui** [comment]
@gutfeeling If you don't have time to work on this, I can propose to do it with my account and give you the full rights on pypi. What do you think?

**Comment by gutfeeling** [comment]
@tupui  Thanks for the offer. Indeed, I don't seem to have any time for this. Would be grateful if you do it with your account and give me the rights.

If you need any info from my side, let me know.

**Comment by tupui** [comment]
> @tupui Thanks for the offer. Indeed, I don't seem to have any time for this. Would be grateful if you do it with your account and give me the rights.
> 
> If you need any info from my side, let me know.

Thanks for allowing me to do this. I just uploaded it to PYPI: https://pypi.org/project/word-forms  🎉 

@gutfeeling Let me know your username on PYPI so I can add you as owner.

Also, I opened #23 with small changes to the readme and the `setup.py` mainly to have a cleaner formatting on PYPI.

**Comment by gutfeeling** [comment]
@tupui This is great news! Thanks so much for stepping up and taking the effort. My username on PYPI is also gutfeeling. https://pypi.org/user/gutfeeling/

**Comment by tupui** [comment]
> @tupui This is great news! Thanks so much for stepping up and taking the effort. My username on PYPI is also gutfeeling. https://pypi.org/user/gutfeeling/

@gutfeeling Sure 😃 . I just added you as owner.

**Comment by gutfeeling** [comment]
@tupui I added you to the contributors in the README.

With this, I am closing this issue.
