### ISSUE TITLE
Use difflib instead of python-Levenshtein for computing similarity ratio

### ISSUE THREAD

**Issue by sajal2692** [gutfeeling/word_forms#17]
The python-Levenshtein library has a [GPLv2 license](https://github.com/miohtama/python-Levenshtein/blob/master/COPYING), meaning that the derived works must be available under the same license. Due to this, I, and presumably others, cannot use this library if we want a different license for works that use the word_forms library as a dependancy. (Thinking about this, it may mean that this particular library should also be GPLv2).

While looking for alternatives to this, I chanced upon Python's own difflib library, and it's [SequenceMatcher.ratio()](https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher.ratio) function. The output of this ratio, is exactly the same as the python-Levenshtein ratios. In fact, there is some overlap between the actual implementations of these libraries, as mentioned in the python-Levenshtein docs. 

Code block to demonstrate this:
```
from difflib import SequenceMatcher
from Levenshtein import ratio

def sequence_matcher_ratio(a, b):
    return SequenceMatcher(None, a, b).ratio()

def compare_equality(a, b):
    print(sequence_matcher_ratio(a, b) == ratio(a, b))

def compare_print(a, b):
    print("Sequence Matcher Ratio: ", sequence_matcher_ratio(a, b))
    print("Levenshtein Ratio: ", ratio(a, b))

>>> compare_equality('continent', 'continence') 
True

>>> compare_print('continent', 'continence')
Sequence Matcher Ratio:  0.8421052631578947
Levenshtein Ratio:  0.8421052631578947
```

I propose we move to using SequenceMatcher, or some other library instead of the python-Levenshtein library. 

I'm already doing this in my own fork, so I can raise a PR for this if needed.

**Comment by sajal2692** [comment]
Using `SequenceMatcher(None, a, b).quick_ratio()` returns the same result, faster than by just using `SequenceMatcher.ratio()`, but it is still not quite as fast as using python-Levenshtein (which is implemented in C).

**Comment by gutfeeling** [comment]
@CubieDev  Would love your comment on this.

**Comment by tomaarsen** [comment]
@gutfeeling @sajal2692 Sorry for the late response, this issue must've slipped my radar. 

Sajal, for context, I added in the similarity measure compution in this commit https://github.com/gutfeeling/word_forms/commit/a9cd983bd09c844ab255fb8992bb67cdc1a0fa14, where I used `SequenceMatcher(None, word, new_lemma.name()).ratio()`, exactly as you propose. I received some feedback on that PR by another user that the `python-Levenshtein` package did the same thing - but faster. As such I wrote another PR which implemented this change. I didn't look too far into it as I trusted the recommendation.

That is my bad, I should have looked further into the complications of using a new module. If using `python-Levenshtein` creates licensing issues, then I would vote to revert back to using `SequenceMatcher`, which is functionally identical.

**Comment by gutfeeling** [comment]
@sajal2692  Feel free to send the PR.

**Comment by sajal2692** [comment]
@CubieDev No worries. This was only brought to my attention when I tried using the library for work, and the stack started complaining. `python-Levenshtein` **is** faster, but the licensing issues exist as well.

@gutfeeling I'll try to send the PR this week. 

Update: Done [here](https://github.com/gutfeeling/word_forms/pull/19)

**Comment by gutfeeling** [comment]
Closing this as the PR is now merged.
