### ISSUE TITLE
How to add domain specific words to this Library

### ISSUE THREAD

**Issue by srinivas365** [gutfeeling/word_forms#26]
I want to add some domain specific words to this library. 
for example: below code gives all word forms for word 'moisturize'
```
get_word_forms("moisturize")
{'n': {'moistener',
  'moisteners',
  'moistening',
  'moistenings',
  'moisture',
  'moistures'},
 'a': set(),
 'v': {'moisten',
  'moistened',
  'moistening',
  'moistens',
  'moisturise',
  'moisturize',
  'moisturized',
  'moisturizes',
  'moisturizing'},
 'r': set()}
```

But when I try below one. I get null set. How can I add word 'moisturizer' and get the above result as it's word forms. Thanks in advance for helping me.

```
get_word_forms("moisturizer")
{'n': set(), 'a': set(), 'v': set(), 'r': set()}
```

**Comment by gutfeeling** [comment]
@srinivas365 The package uses [Wordnet](https://wordnet.princeton.edu/) as the underlying dictionary. Wordnet unfortunately does not have the word "moisturizer". 

I also don't know if there is a way to add your own words to Wordnet.

So, this is not really an issue of this package. I am going to close this issue.
