### ISSUE TITLE
"Fished" not showing up in results

### ISSUE THREAD

**Issue by ivanmkc** [gutfeeling/word_forms#27]
I was running a simple test.

`get_word_forms("fish")`

However, "fished" is not showing us as expected under "v". 

Actual results:
`{'n': {'fisher', 'fisheries', 'fishery', 'fishers', 'fishings', 'fishing', 'fish'}, 'a': {'fishy'}, 'v': {'fish'}, 'r': {'fishily'}}`

**Comment by ivanmkc** [comment]
This has quite a lot of issues with past tense.

**Comment by tomaarsen** [comment]
This is due to `fish` not appearing in [en-verbs](../blob/master/word_forms/en-verbs.txt). `word_forms` is only able to find verbs other than the lemma if the lemma is in that file. It should be noted that `word_forms` is definitely not perfect.

**Comment by gutfeeling** [comment]
Yup, exactly what @tomaarsen said. 

Our approach is limited to Wordnet and the [en-verbs](https://github.com/gutfeeling/word_forms/blob/master/word_forms/en-verbs.txt) list. Neither is complete. 

Still, I sympathize with your issue @ivanmkc, but I don't have any ideas to fix it in a scalable way. Adding missing verbs manually is effort intensive with marginal benefits. 

So I am going to close the issue. If you have any suggestions, you can still comment here.
