### ISSUE TITLE
Not working for past tense input

### ISSUE THREAD

**Issue by nicholascarroll** [gutfeeling/word_forms#3]
Tried your function get_word_forms on 'walked'. It did not work. Here is the output:

In [17]: get_word_forms("walked")
Out[17]: {'a': set(), 'n': set(), 'r': set(), 'v': set()}

By contrast for the lemma, it does work:
In [16]: get_word_forms("walk")
Out[16]: 
{'a': {u'walking'},
 'n': {u'walk', u'walker', u'walkers', u'walking', u'walkings', u'walks'},
 'r': set(),
 'v': {u'walk', 'walked', 'walking', 'walks'}}

So maybe reduce to the lemma first?

**Comment by gutfeeling** [comment]
This should be fixed with #10
